### ISSUE TITLE
Past habits & data gone

### ISSUE THREAD

**Issue by inkymama** [goodtohear/habits#39]
I backed up my data before updating to iOS 8 (emailed it to myself so I could just tap on the "restore data" link). I updated, and everything was gone. I tried to restore data, and it restored, but once I exited the app, it disappeared. I uninstalled, reinstalled, attempted to restore data, same thing (disappeared). I did that 4 times, even restarted phone between reinstalling two of the times. 
Even weirder--I created a new habit ("take a picture"), and went through and tapped every single day back to January 1st, since I'm doing a "365" project. Once I exited the app, all of the marked off days previous to the day I installed, disappeared. I'd sure like to have this work again! Help!

**Comment by inkymama** [comment]
Also--paused habits are super confusing. How do you pause a habit so that if you're taking a break, it doesn't count against your streaks?

**Comment by michaelforrest** [comment]
Hopefully v2.0 fixes this problem for you. You should be able to restore the data exported from the old version of the app.

**Comment by michaelforrest** [comment]
I am thinking that 'paused' habits should actually be 'archived' habits. This will be easier to show now that I have a button with text on it instead of a 'pause' icon.

I will not be implementing per-habit 'pausing' as a matter of principle - it goes against what is required to build a habit. However, I will be adding an 'on holiday' mode or something so that you can pause _all habits_ for a few days. When I figure out how the user interface will support this.
