### ISSUE TITLE
Problem with saving after upgrade to iOS 8

### ISSUE THREAD

**Issue by alex---andra** [goodtohear/habits#42]
After I upgrade system to iOS 8, any of my checks are saving. When I close app and open it again everything is gone. Reinstall and everything doesnt work

**Comment by needhelpnow** [comment]
This is happening to me too.  Since upgrading to iOS 8 Good Habits doesn't save your checks, even if you don't close app, the next day all your checks are gone.  Deleted, reinstalled but that didn't fix the problem.  Please update app for iOS 8 so I can continue with my good habits, it's been so helpful in my life, I really appreciate it, thank you!

**Comment by michaelforrest** [comment]
Closed in v2.0 - now available.

**Comment by needhelpnow** [comment]
Thank you!
